name: ml-for-chemists-tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.19.5
  - deepchem=2.4
  - h5py
  - jupyter
  - tensorflow-gpu=2.2
  - tensorboard=2.2
  - tensorflow-estimator=2.2
  - rdkit
  - scikit-learn
